FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install
RUN npm install pm2 -g

# Bundle app source
COPY . .

# Expose port 3005
EXPOSE 3005

# Run the app
CMD [ "pm2-runtime", "server.js" ]
